### ISSUE TITLE
network ip address not shown on home after boot

### ISSUE THREAD

**Issue by nerone** [monome/norns#1333]
after fresh boot network IP address on HOME (K2 on HOME) is blank when there is an activated connection (norns shield + raspi 3b+ on 5ghz wifi in my case). when i go to SYSTEM -> WIFI i see STATUS: activated, and returning on HOME the IP magically appears.

**Comment by dndrks** [comment]
hi @nerone  -- thank you for the report! unable to repro, but I'm also working on a 2.4ghz band. i'm curious if this is issue is reproducible on your 2.4 as well?

**Comment by ngwese** [comment]
apologies, i have been meaning to respond after i had a moment to go back through the code but i do believe the behavior is a limitation with how the status on the home screen interacts with the wifi menu.

the short version is that the ip information is not repeated queried because it is slow to obtain and the logic is currently in lua so this can’t be done in the background. the wifi menu does do this expensive operation because it has to in order to function - it then stores the address for use in the home screen 

we may have code which checks for an ip once when starting up matron (which would explain why is occasionally appears if the network connected quickly on boot)

**Comment by tehn** [comment]
perhaps we should just remove the IP address from the HOME/INFO screen, just keeping it on the WIFI screen? as finding your IP address is a somewhat atypical option (provided norns.local should mostly work, and the IP address will certainly show up in the WIFI screen along with signal strength info, which is good for debugging a not-appearing norns)

**Comment by ngwese** [comment]
removing it is one strategy. i can take a quick peek to see if there is any easy fix. i believe the current behavior has existed since the wifi menu was reworked.

**Comment by nerone** [comment]
i'm just wondering if we would query for ip address only when switched to SYS INFO screen would it be less expensive operation? it probably should...

**Comment by tehn** [comment]
i'm still considering just removing the IP from the info screen.

do you find yourself frequently needing to reference the IP address? perhaps instead we should attempt to debug why some user setups can't detect `norns.local`

**Comment by dndrks** [comment]
isn't IP address necessary to shuttle OSC back to TouchOSC or Max?
also, multi-unit setups are pretty common now thanks to shield, so being able to specify which device you want maiden to target is helpful.

**Comment by tehn** [comment]
you can still see IP via SYSTEM > WIFI

but yes, it's probably legit to keep IP top level.

do touchosc/max not resolve norns.local?

for multi-unit we should make a walkthrough doc for renaming your hostname (norns.local to something else ie othernorns.local)

**Comment by catfact** [comment]
@dndrks for multiple norns maybe it's worth documenting how to change hostname. 

@tehn i for one have always sporadically lost the ability to resolve the norns hostname (through DNS caching or whatever), so having the IP on screen is very useful. seems to often happen after running update scripts.

**Comment by dndrks** [comment]
@catfact we have this bit: https://monome.org/docs/norns/wifi-files/#hostname, recommending `sudo raspi-config`. please lmk if that doesn't fit your own practice tho!
