### ISSUE TITLE
grid rotation to 90/270 deg not usable anymore

### ISSUE THREAD

**Issue by kasperbauer** [monome/norns#1418]
When rotating the grid to 90 / 270deg, the lower half of the grid won't light up anymore.
The buttons seem to respond correctly though.

Scripts like metrix / skylines and also the grid-test show this problem.

This seemed to appear after the 210607 update, where also the support for the 2021 grid was intruduced.

(I'm using norns shield with a 2012 or 2013 grid)

**Comment by okyeron** [comment]
Was looking at device code with tilt along with my grid-test script and maybe found what's happening:

Since [this changed from 4 to actual number of quads](https://github.com/monome/norns/blob/11dcbd33b793137499d89950d297d759f58568fe/matron/src/device/device_monome.c#L139), the wrong quads are getting the LED refresh (or the wrong ones are marked dirty) when the device is rotated?

**Comment by catfact** [comment]
i'm going to ping @tehn on this also.

on norns, it is vital that we update the device state both at the lua level `grid` table, and at the "driver" level (`device_monome.c`) to reflect rotation changes instead of just relying on libmonome to do it. that is because the lua API does not expose libmonome directly. 

there are two options:
- 1. every device gets 4 quads worth of buffer space, update/choose which quads to send based on rotation
- 2. don't even send rotation commands to libmonome, handle rotation ourselves in `device_monome.c`. that means:
  -a.  modify X,Y in the handler here before riasing events: https://github.com/monome/norns/blob/main/matron/src/device/device_monome.c#L171-L177
  -b. modify how packed LED data for quads is constructed on refresh: https://github.com/monome/norns/blob/main/matron/src/device/device_monome.c#L131

in either case, certainly the lua tables (vport and device) need to update in response to setting rotation at the lua API level.

**Comment by catfact** [comment]
i suppose the simplest band aid is just to continue to use libmonome rotation, but also take rotation into account in the  refresh routine (for the purposes of deciding which quads to send, but without modifying the layout of data within each quad.)

**Comment by tehn** [comment]
on it. doing some other libmonome debugging as it happens

**Comment by catfact** [comment]
ok - sorry for noise on this - on reflection the real issue is just that we changed the quad count from 4 for all devices.

(why did we do this>? are there some devices that can't handle upates to non-physically-addressed LED positions?)

because the thing is - if a 128x64 device allows rotation, then it **should** be considered a 128x128 device at the level of both the lua API and `device_monome.c`.

**Comment by okyeron** [comment]
I threw my test code up in a branch for reference.

With these changes, everything seems to work as expected

https://github.com/okyeron/norns/tree/rotation-test

**Comment by catfact** [comment]
heres the diff for that
https://github.com/monome/norns/compare/main...okyeron:rotation-test

it's fine - it's equivalent to my sugggestion but also dynamicslly updates the lua representation of the device dimensions - which is good. thanks!

but my question remains, and concerns this line:
https://github.com/monome/norns/compare/main...okyeron:rotation-test#diff-
4f52f40200f35bb22c3fa7098c08becae2ed172ad4a92d646d0cbe753b028a84R123

where you effectively revert the change that caused the underlying issue. but this change was made for a reason, i just don't know or can't rememnber what. (IIRC something about either the new grids or some DIY grid not working with the rotated quad offsets. so maybe this is/was actually a grid-st firmware issue.)

**Comment by tehn** [comment]
unfortunately i also can't recall why this change happened. it may have
been preemptive optimization. i'm fine merging this back in.

libmonome should not send irrelevant serial packets (ie, out of range), and
the grid firmware should ignore out-of-range as well (though it's better to
reduce bus traffic rather than rely on this) --- possibly related, i'm
trying to track down the "resource not available" bug in libmonome

**Comment by catfact** [comment]
i am almost positive there was some device that couldn't handle this for some reason. 

there are edge cases / race conditions: it's possible for rotation command to be processed while there is still a dirty quad waiting to be transmit, with an offset valid under old rotation but not under new rotation.

so agree that easiest thing is if every component of the process can handle any quad offset without breaking.

**Comment by tehn** [comment]
fixed
