### ISSUE TITLE
need hook for script stop

### ISSUE THREAD

**Issue by p3r7** [monome/norns#1430]
currently defined hooks allow for powerful mods when scripts are loaded.

on the other hand, when developing "global" mods, that take effect even when no script is loaded, we are missing a hook in the lifecycle for the use-case when the user stops/unloads a script (global menu K1+K3, stop button in maiden web ui).

this missing hook is represented in red in the diagram bellow:

![norns_lifecycle](https://user-images.githubusercontent.com/11557146/133775203-edef8a82-b2da-428b-bbe5-5f71fed52c62.png)

also, please note that the name of `script_post_cleanup` is somewhat counterintuitive, as it appears to run even when no script loaded beforehand (e.g. before first script load) but doesn't run when stopping a script...

**Comment by ngwese** [comment]
the fact that `script_post_cleanup` is not called when the key combo or maiden stop button are pressed does look like a bug/omission.

the hooks by their nature are going to mirror the internals of matron and the menu system code. to the best of my knowledge the user action of “stop” is internally just a “clear” without a subsequent “load”. the potentially surprising behavior that `script_post_cleanup` is run even in cases where no script was previously running is probably best handled with additional documentation.

**Comment by p3r7** [comment]
ah, yes the intent of `script_post_cleanup` seems to be the same as the one i thought missing (in red in the diagram).

> the hooks by their nature are going to mirror the internals of matron and the menu system code. to the best of my knowledge the user action of “stop” is internally just a “clear” without a subsequent “load”.

agreed, hooks represent internal transitions (implem) and not the front-facing user API.

in my own stuff, i generally like to have a thin gw abstraction layer to dissociate the API entry points from the implem. basically what translates from _commands_ to _events_ in _DDD_ lingo.
but given the low complexity of the norns user API and the fact that there is no need for validation / transactions, a dedicated method for the "stop" is unnecessary.

**Comment by tehn** [comment]
`script_post_cleanup` is called on manual stop, correct? if it's not, that's a bug for sure

**Comment by p3r7** [comment]
i've just tested again.

`script_post_cleanup` is NOT called on manual stop (both from global menu & from maiden web ui).

furthermore, i took a look at the few mods i did, which enrich params menu differently depending on whether a script gets loaded or not. 

i specifically exploit the fact that `script_post_cleanup` doesn't get called on a "stop" to differentiate it from a script switch (using a state var, [set](https://github.com/p3r7/osc-cast/blob/main/lib/mod.lua#L91) and [test](https://github.com/p3r7/osc-cast/blob/main/lib/mod.lua#L121)).

if `script_post_cleanup` gets called in every case i will not be able to differentiate between those use cases... :cry:

**Comment by ngwese** [comment]
sounds like a bug that needs fixing and it sounds like there might be a use case worth differentiating.

i’m happy to investigate. if there are links to one of the mods which is dependent on the current behavior i’d like to get a feel for what it is trying to do.

we have the option of introducing new hooks if appropriate but i think it would be best to be cautious and deliberate when doing so.

**Comment by p3r7** [comment]
> if there are links to one of the mods which is dependent on the current behavior i’d like to get a feel for what it is trying to do.

See [osc-cast](https://github.com/p3r7/osc-cast) which forwards param changes as OSC messages by wrapping each `param.action` methods.

it needs to be called after `script.init` to catch a newly loaded script's params.
when no script gets loaded, i call it after `script.clear` instead to catch global params.

i now realize that i could call it systematically in `script.clear` & `script.init`, the only drawbacks being that:
- the mod params section would appear before the script's in the menu, which for some reason i OCD'ed over
- i would need to blacklist the mod's own param from the `param.action` overloading to prevent an infinite callback loop

**Comment by tehn** [comment]
maybe override `init` instead of `script.init` ???

**Comment by p3r7** [comment]
my bad, edited

**Comment by ngwese** [comment]
i've done some initial investigation and indeed when a script is "cleared' by key combo or the stop button in maiden the `script_post_cleanup` hook is not called as one might expect. it turns that there is more than just a missing hook invocation - there are inconsistencies in how cleanup is perform when a script is "cleared" versus what happens when switching scripts (which is effectively "clear" + "load").

the `script_post_cleanup` hook intentionally runs right after the scripts own `cleanup` function is called but before all the global device, callback, and parameter bits are reset to normal. the thinking was that if a mod added it's own parameters it may want to persist values automatically when the script is stopped (for example). 

in addition to the missing hook invocation i thing the current script handling has two additional bugs:

(1) the active scripts `cleanup` function is only called when switching between scripts, it is not called when stopping/clearing a script.

(2) calling `script.clear` (as maiden does) does not switch the MENU ui. when using the K1 + K3 combo this is a non-issue because one must have already switched to the MENU before hand. clicking the stop button in maiden will leave the script's UI on screen (there also appears to be some residual callback code for enc as well).

i think the best course is to make the cleanup and hook invocation behavior consistent for both the script clear and the script switch cases - from the perspective of matron / MENU system there isn't any difference between those two cases.

**Comment by tehn** [comment]
fixed by #1438
