### ISSUE TITLE
proposal: UI components

### ISSUE THREAD

**Issue by andr-ew** [monome/norns#1450]
first off: by UI component I mean: a thing that **takes input** (keys, encoders, grid, arc, HID) > **turns the input into data** > **takes the data and draws something somewhere** (norns screen, grid, arc). think of how you might abstract a single fader on the grid to make it reusable, for example.

what I’m proposing is more of a broad standard / template for what a UI component is and a small API to set up an input & render loop. users like me could share libraries of components that other people could use to build a script. when there’s not a component made for what you need to do, you can easily make your own and use it alongside components made by others.

my idea is that components are pure functions, the components are called inside of a “render loop” function provided by the user. when there’s input, the render loop is called & the components generate an ordered list of routines to process input. when the output is dirty, the render loop is called & the components generate an ordered list of routines to redraw the output.

for example (pseudocode):
```
render_loop(function()
	component1{}
	component2{}

	if meta_page then
		component3{}
	end
end)
```
the component function would cooperate with the API “behind the scenes” on each call to pass along an input hander & a redraw handler. the render loop would probably overwrite the various input handlers as needed (`key`, `enc`, `g.key`, etc and also `redraw` if the screen is used).

using the render loop as opposed to tables is great because the user can build an interface dynamically with regular if statements & for loops (i.e. for pagination, or if you want 300 sliders). using a single render loop rather than the default separate input callback & redraw loop is great because you don’t have to repeat every component call & the pagination logic in each of those functions. keeping components functional/dynamic & keeping state separate from the UI logic has been very good practice in my experience (i.e. in a paramset).

I’m proposing that components are functions called with a table argument, and the only(?) standard argument would be one called `state`. `state` would provide the current set of data when the affordance is drawn, and a callback to update that external data on input. any data that needs to be modified by the affordance & persist between frames would need to be in the state. other arguments would set up things like x & y positions, an `action` callback, which encoders or keys the component is mapped to, brightness levels, rotation rate, etc.

example:
```
grid_toggle{
      x = 1,
      y = 1,
      state = { some_value, function(state) some_value = state end }
}
```

that `state` argument looks possibly confusing, but I grouped things together so that the process could be easily automated with a set of provided functions & some kind of standard global state table (with shortcuts for “binding” state to a param or other external data sets):
```
grid_toggle{ state = state.new(‘grid_thing’) }
grid_toggle{ state = state.from_param(‘toggle_param’) }

-- to access:
state[‘grid_thing’]
params:get(‘toggle_param’)
```

while not strictly necessary, I also think it’s a good idea to standardize `state` (or, uhh, `state[1]`) as a table, so that the component has agency to add & remove extra bits of data for things like key detection, timers, etc - that way the user doesn’t have to think about whether to explicitly provide space for these things or not. a key such as `value` could standardize the “user land”/“public” section of data to access or modify (toggle state, fader position, etc).

of course, stateless components would also be supported, these would probably just not take input & only provide a redraw routine to the API.

-----------------

**big picture**: I’m submitting this as a feature to the upstream norns library because I think it could be _really_ interesting as a community development, if the need is there more widely, and because if implemented well it could lower the barrier to entry for more complex UI-driven scripts, especially on the grid. I’ve already solved this issue for myself (between 3 and 4 times) & have experienced the benefits of designing full scripts with a library of components vs. raw functions. I think it’s great in all sorts of contexts, but working on my own i’ve never been able to make it ergonomic & simple enough for other people to be able to pick up intuitively without sacrificing flexibility. really just putting out the idea to see if ya’ll think it’s interesting !

(p.s. would you rather just look at code???)

**Comment by catfact** [comment]
we could take a PR to add `nest_` to `norns/lua/lib` if that interests you.

i don't think this level of abstraction hits the "sweet spot" for everyone. a lot of us prefer to have a more shallow hierarchy, especially when the "low-level" layers are as simple as the grid API and the params API.

( https://2019.jsconf.eu/johnny-austin/finding-your-abstraction-sweet-spot.html )


but the `lib` folder is intended for stuff like this. worth mentioning though, that we've not seen a lot of adoption of `ui`, `sky` etc. in fact we will probably retire `norns/lib` and `norns/ext`, instead recommending that libs be distributed outside the norns repo (included as submodules in scripts, say.)

**Comment by andr-ew** [comment]
> we could take a PR to add `nest_` to `norns/lua/lib` if that interests you.

cool - to clarify - this is kinda another iteration on that idea, not something I've written already. but yea it's exactly the same level of abstraction & solves the same problem. I'd probably just port the same components/affordances to the new system. but yea, probably not worth the effort if I'm the only one excited about it :-) this is really just me gauging interest

**Comment by catfact** [comment]
Im sure there are others who would be excited. But just be aware that not everyone using grids needs it.

 If you want to have a real conversation about why/how, we could do that (maybe in another channel)

For now, the question id ask is - why is this a new proposal given that `nest_` exists? Do you just want more visibility / contributions for `nest_`?

**Comment by andr-ew** [comment]
> For now, the question id ask is - why is this a new proposal given that `nest_` exists?

nest uses tables with internal state as components & relies on callbacks for automation, conditional rendering, dynamic properties, and external states. it works, but the ergonomics feel very different from basic lua programming & the rest of the ecosystem. i'm interested in designing a system that's simpler & more consistent with the rest of norns.

nest was also designed for a fixed set of components made by me, whereas this functional approach is more practical as an collaborative or purely organizational system since folks can roll their own components fairly easily (my proposal is just to submit a common render loop to upstream `lib/`, not the components themselves).

**Comment by catfact** [comment]
i see okay. sorry i forgot how nest_ is structured. so you like what that lib does but you want to do it in a different way. (more FP than OO.) all well and good. but it should still be a library, not in core, and it seems to me there are engineering issues you haven't really worked out.

again, we can maybe speculate and chat about details in another channel besides the norns issue list. but in brief:

- core should be stable, fast, lightweight, easily maintained, make minimal assumptions, and  support a variety of paradigms. e.g. while i don't actually think of things like the `grid` class as _low level_, it is a thin/shallow layer of abstraction which is how we like it. (there is very little lua code between `g:led()` and the underlying C system.) 

- specifically, i'm not convinced that FP gives you a lot of benefit here and comes with significant pitfalls. i don't know that i have time to get into a lot of details and this probably isn't the best forum for spitballing anyway. 

but in a nutshell, you are moving complexity out of the components themselves and into the management/validation of `state`. if you actually have hundreds of components this will become a big problem. you will have to be very careful about what lua is really doing under the hood with allocations etc, if the idea is that each component is pure and returns a new copy of its state every time something changes.  (with especial care being given to recursion, and to any component function that builds strings.) i suppose some sort of non-pure manager will be responsible for marshalling changes to the global state.

you may be thinking of frameworks like Flutter, which is very performant and (while not pure FP) does borrow some ideas from that area and looks sort of like what you are describing. flutter is performant because the whole stack is engineered in a certain way: separate task runners for IO/UI/rendering, AOT compilation. naively implementing the same patterns in plain lua is not going to work out as well.

so i think if i were you, my next step would be to start proving out your basic design proposal in a new library. it doesn't have to be on norns and can be small in scope. you will need to pay attention to what these state objects are actually pointing at and when things are being GC'd.

**Comment by andr-ew** [comment]
> and in the end this would be a library that people can use or not. we won't be forcing the use of a global component state table for all script authors.

naw, submitted for inclusion for `norns/lua/lib` (same as `ui.lua`), not `core` & I'm definitely not trying to force all script authors to do something. if you're getting rid of `norns/lua/lib`then I guess there's nothing to consider anyway. thanks for the feedback though ! I haven't heard of Flutter.
