### ISSUE TITLE
string.char() argument value above 127 causes loss of functionality

### ISSUE THREAD

**Issue by 256k** [monome/norns#1701]
given the example code

```lua 
local var = 40

function init()
redraw()  
end

function redraw()
  screen.update()
end

function drawstring(text)
screen.clear()
screen.move (64,24)
screen.text_center(text)
redraw()
end

function enc(e,d)
  if e == 3 then var = util.clamp(var + d, 40, 1000) end   
  print(var,":", string.char(var))
  drawstring(string.char(var))
end

```
this code will incrementally print to maiden and to the screen  text the corresponding ascii character to the value `var`
but as soon as the value reaches beyond 127 both maiden and the screen updating will cease to function.

I was not able to get any log information regarding this. seems to be a sort of silent failure, at least from what i can tell.

EDIT: perhaps something relating to a char definition somewhere that should be unsigned but isn't and is causing an overflow?

**Comment by catfact** [comment]
the `string` library only handles the 7-bit ascii character set. so values above 127 are not legal (they would be encoded with utf-8 or something.) officially `string.char` is undefined for those values. in practiuce it will just return an illegal string. 

for example `string.char(128)` creates a byte array containing 1 value, 128. this isn't a printable string - it's like half of a single-character utf-8 string, or a single invlaid ascii value.

so anyways the proximate cause of the problem (hang or whatever) seems to be passing an illegal string to `drawstring`, which i don't think is a function i recognize. 


incidentally, in testing the printing of an illegal string like `x = string.char(128); print(x)`, i've noticed:
you jus
- `matron` behaves like lua 5.3 standalone REPL - prints `?`. 
- the maiden REPL crashes something! i assume it's our websocket wrapper.

that is probably worth fixing. still, it's sort of a contrived stress test - if you actually need to work with utf-8 byte streams, use lua's `utf8` library instead of the `string` library. this will at least result in legal byte sequences, so e.g. this will work in maiden REPL:

```
xx = utf8.char(b)
<ok>
print(xx)

```

**Comment by catfact** [comment]
i'm closing this as "won't fix" since it reflects a basic misuse of the lua standard `string` library.

**Comment by 256k** [comment]
I understand that this is a misuse of the library, i guess my point of opening up the ticket was, like you said, avoiding maiden or the screen drawing to "break" but fair enough if you feel this is only a small edge case and not worth looking into.  i understand

**Comment by catfact** [comment]
ok fair enough. but again - `drawstring` isn't part of norns or lua. 

i can also confirm that `screen.text()` also causes problems / hangs the UI when given an illegal 1-byt string. but i personally don't think it's worth it for us to chase down all the places in the stack that could have problems with that (likely including third-party libraries like cairo and nanomsg.) if someone is motivated (you?) that's fine with me.

take this script for instance. all problems can be avoided by using `utf8` instead of `string` on L22:

```
a = 200
b = 255

init = function()
  redraw()
end

redraw = function()
  screen.clear()
  screen.level(10)
  screen.font_face(0)
  screen.font_size(10)
  local x = 0
  local y = 10
  for i=a,b do
    x = x + 10
    if x > 60 then 
      x = 0
      y = y + 10
    end
    screen.move(x, y)
    
    -- this is ok, returns 2-byte string
    z = utf8.char(i)
    -- this is bad, returns 1-byte illegal string, 
    -- potentially hangs any API that requires valid ASCII or UTF8!
    -- z = string.char(i)
    print(i)

    -- either of these will cause an issue with the illegal 1-byte string
    print(z)
    screen.text(z)
  end
  screen.update()
end
```

```
```
