### ISSUE TITLE
reflection not saved successfully when saving immediately after recording 

### ISSUE THREAD

**Issue by jaseknighter** [monome/norns#1788]
calling `reflection:save(tbl,filename)` immediately after `reflection:set_rec(0)` results in the `length` property of the reflection instance's data table being saved as 0 instead of the proper value (calculated by line 151 of reflection.lua (`pattern_data.length = self.endpoint / 96 -- 96 ppqn`).

i can work around this by putting a delay in the code of my script that saves the reflection, like:

```
reflector_tab:set_rec(0)
local rec_clock
rec_clock = clock.run(function()
  clock.sleep(0.1)
  reflector_tab:save(reflection_data_path .. rec_id)
  clock.cancel(rec_clock)
end)
```

perhaps the reflection.lua code should be updated so this workaround isn't required? 

>3333

**Comment by tehn** [comment]
seems like an initialization bug? @ryleelyman @dndrks

**Comment by ryleelyman** [comment]
no, i think this is happening because most of reflection is asynchronous / clock-based, while `save` is synchronous?

i _am_ a little surprised that `set_rec` is the thing here that is at issue. `endpoint` is only updated when `reflector_tab:end_playback()` is called.

from the context you gave it's not clear how frequently you're intending to save, but i might suggest putting `save` inside an `end_callback` as the currently intended solution, rather than your workaround?

**Comment by jaseknighter** [comment]
thank you for the clarifications @ryleelyman. in the script where i encountered this, saving is initiated by the user, i'd say somewhat infrequently. 

i will try putting `save` in an `end_callback` and assuming this resolves the issue, i'll then close out this bug.

**Comment by jaseknighter** [comment]
closing...the issue is not a bug and is resolved when saving in a `end_of_rec_callback` callback as suggested by @ryleelyman. <3
