### ISSUE TITLE
sandboxed environment for lua scripts and REPL

### ISSUE THREAD

**Issue by catfact** [monome/norns#258]
i think we can and should use a dedicated table as the pseudo-global environment for executing the current script and REPL chunks. that way users can use globals without fear.

https://stackoverflow.com/questions/35910099/how-special-is-the-global-variable-g
http://lua-users.org/wiki/EnvironmentsTutorial
http://www.lua.org/manual/5.3/manual.html#pdf-_G

**Comment by pq** [comment]
more food for thought: if i understand the implications, i think sandboxing could also make development of scripts with module dependencies easier[*] and lessen the need for some kind of module re-load facility in maiden (https://github.com/monome/maiden/issues/22)


[*] tl;dr: the rub is that since modules are not automatically reloaded, changes to them do not get picked up in dependent scripts/modules leading to potential confusion when making changes.

**Comment by ngwese** [comment]
for user modules (those in dust) one possible way to handle this is to monkey patch the require function in the sandboxed environment allowing us to keep track of modules loaded explicitly by a user script... once we know what was loaded we can certainly clear out the package.loaded global as needed. 

system modules (part of norns) are still problematic but given that they are loaded in multiple places potentially. 

the evaluation environment for the repl commands might be the more challenging aspect since the lifetime of the repl spans multiple scripts

**Comment by tehn** [comment]
primary fix https://github.com/monome/norns/pull/436

closing this, but referencing #557 #559
