### ISSUE TITLE
dropped OSC messages

### ISSUE THREAD

**Issue by catfact** [monome/norns#292]
we appear to be dropping OSC messages from lua->sc with some number of multiple messages attempted "simultanously"

**Comment by tehn** [comment]
stumbled upon this while working on mlr, which spews ~300 OSC packets at softcut as setup. (i can likely optimize this, but just to have a number).

i was seeing failure when doing a new bootup of matron. the issue was, `cleanup` was getting run twice, so `softcut.reset` was getting run twice also, which itself shoots out 175ish  packets.

my problem was resolved by fixing the double-cleanup, but i was seeing crone receive about 400 packets during the double-init... which means about 250 were getting dropped. (which is why i noticed mlr not working right).

we might consider moving crone to IPC to open up some OSC bandwidth? or just make the buffer bigger and be ok with timing slop? these massive sends i really only expect for initialization stuff...

side-option specific to softcut... i could implement a single `reset` command and do all the default vals inside crone

**Comment by catfact** [comment]
Hard coded reset is easy pickings and solves immediate problem

Another simple thing would be making more cryptic abbreviations for OSC paths

Switching transport layer is actually pretty PITA at this point but of course doable given time. Would try to keep OSC as option in that case for crone compatibility with other environments.

**Comment by tehn** [comment]
keeping crone OSC friendly makes a ton of sense, i neglected to consider that.

shortening OSC commands where possible is good idea. yesterday @antonhornquist suggested`/command` -> `/cmd`

would `softcut` -> `sc` be acceptable?

i'll work on a crone-based sc reset.

**Comment by ranch-verdin** [comment]
Would be great if any IPC transport would provide file descriptor and work with poll and select, for event loop paradigm.

According to a quick bit of googling this morning POSIX IPC or nanomsg would support that, but sysV IPC wouldn't.
