### ISSUE TITLE
clean up websockets in ws_wrapper on forced exit

### ISSUE THREAD

**Issue by catfact** [monome/norns#372]
nanomsg / websocket doesn't seem to (always) exit cleanly after `stop.sh`. that script is just `killall`. needs signal handler

**Comment by ngwese** [comment]
i've started to look into this, specifically:

- [x] fix argument passing in `ws-wrapper` so that child processes have valid `argv` not the process environment
- [ ] have `ws-wrapper` setup process groups (if need be)
- [ ] add signal handler to `ws-wrapper` which closes sockets on `SIGTERM`
- [ ] ensure systemd units kill entire process group not just the top process

...there is probably more stuff but the overall goal is to have `systemctl restart norns-{matron,crone}` actually work.

**Comment by simonvanderveldt** [comment]
Does anyone know if any progress been made on this?
Noticed that stopping or restarting `norns-matron.service` doesn't work, the matron process keeps running.

Is this an issue with `ws-wrapper`?
It does seem to be working for `norns-crone` (on the current 181101 release, so the sclang wrapper). Both sclang and supernova get stopped when stopping `norns-crone`.

**Comment by tehn** [comment]
`systemctl restart norns-matron` does indeed work for me.

did you run the newest 2.0 update?

**Comment by ngwese** [comment]
i had completely forgotten about this ticket. i did tweak a few things in `ws-wrapper`. iirc things were working well enough that i stopped.

i regularly restart `matron` via systemctl on dev

**Comment by tehn** [comment]
this seems to no longer be an issue. @ngwese can you confirm?
