### ISSUE TITLE
Generic i2c functions

### ISSUE THREAD

**Issue by okyeron** [monome/norns#474]
Would it be possible to update/modify i2c.c to allow for generic i2c read/write functions (such as communicating with other devices)?

**Comment by tehn** [comment]
you could likewise just pass `os.execute` lua calls to `i2cset` or an external python script (or similar) if you're doing low-bandwidth i2c interactions.

**Comment by catfact** [comment]
@okyeron i'm not totally understanding this feature request since we don't have an external i2c port? you wanna add generic i2c interface in lua for running on other hardware? won't scripts that use it not work right on monome norns?

in other words, can you either a) assign yourself, b) do this in a fork for your specific HW, or c) close?

**Comment by tehn** [comment]
this is not in the scope of the norns hardware. but if you add compatible functionality to your fork please submit a PR for review.
