### ISSUE TITLE
add parallel processing for polyphonic egines

### ISSUE THREAD

**Issue by catfact** [monome/norns#481]
use `ParGroup` to distribute processing load for polyphonic engines (polysub, softcut, etc etc)

require supernova (issue #435 )

**Comment by catfact** [comment]
actually guess there are others that need the same treatment.

**Comment by simonvanderveldt** [comment]
I think part of this is fixed by https://github.com/monome/dust/pull/171, right?

**Comment by catfact** [comment]
yes but not for all engines

**Comment by tehn** [comment]
i believe all poly engines were converted, but we can leave this open to investigate the top-level `ParGroup` as @catfact mentioned

**Comment by antonhornquist** [comment]
https://github.com/monome/dust/pull/183 fixed polyphonic engines

i'm weary of making the top-level group a `ParGroup`. using `ParGroup` should be the exception rather than the rule since it breaks node order of execution (which in itself is a pretty hard concept to grasp, especially for SC newcomers).

**Comment by catfact** [comment]
i agree that predictable OOE should be the default, that parallelization should be explicit in places where it makes sense, and think we can close this issue.
