### ISSUE TITLE
Wifi connection says 'failed' but actually connected

### ISSUE THREAD

**Issue by rross101** [monome/norns#521]
New update installed. Connection to wi-fi shows `status: failed` on display but actually it's fine.

**Comment by ranch-verdin** [comment]
probably a bit late, since it seems wifi.sh will be replace by networkmanager now.  However, in case teething problems with NM can't be ironed out, just a quick note what could be done to further battle-harden this unholy shell script:

https://github.com/monome/norns/blob/master/wifi.sh#L44

this invocation:
`sudo wpa_cli status|grep wpa_state|sed -e s/wpa_state=//` != "COMPLETED" ]

looks like an obvious weak point of the little beast, it could be hardened a bit.  Could potentially gerry-rig something to log the entire output of sudo wpa_cli status and make that available for debugging the field failures which have clearly been plaguing wifi.sh.

These points also look bad, since the error message is duplicated for different error conditions:
https://github.com/monome/norns/blob/master/wifi.sh#L109
https://github.com/monome/norns/blob/master/wifi.sh#L113

oh, and sorry for not coming back sooner to fix this buggy piece of crap!
