### ISSUE TITLE
device monitor arbitrary paths

### ISSUE THREAD

**Issue by okyeron** [monome/norns#525]
I'm looking for some sort of enhancement to allow for 3d party tty devices* to be recognized by norns alongside regular monome devices.

`device_monitor.c` has the following
```
// watchers
// FIXME: these names / paths are really arbitrary.
static struct watch w[DEV_TYPE_COUNT] = {
    {
        .sub_name = "tty",
        .node_pattern = "/dev/ttyUSB*"
    },
//..etc
```
* I'm working on a couple of Teensy based devices right now. One is a DIY grid, another an encoder knob box. Both can speak serialosc/libmonome so for testing I've had to comment out the current "tty" node_pattern and replace it with `.node_pattern = "/dev/ttyACM*"`

Thus it would be great if this watcher section would allow for multiple types of tty devices (for when I get around to releasing these diy projects for others to use).

**Comment by catfact** [comment]
at the moment, i guess it would work with just `tty*`. (since we are already checking for usb subsystem as noted in issue #527.) 

otherwise, could replace `fwatch` with regex and use more sophisticated pattern matching.

if you want to use something thats not libmonome-compatible, it gets more involved of crouse.

**Comment by okyeron** [comment]
Did a quick test and changing to  `.node_pattern = "/dev/tty*"` seems to work ok for my DIY grid
