### ISSUE TITLE
ControlSpec params don't allow selection of every integer value

### ISSUE THREAD

**Issue by markwheeler** [monome/norns#529]
For example, if I'd like to have a param for setting a MIDI value from 0-127 I might try:
`params:add_control("Test", ControlSpec.new(0, 127, "lin", 1, 64, ""))`

However, despite specifying `1` for the `step` argument, turning the encoder skips some values. For example I cannot dial in 66 - however slowly I turn it jumps from 65 to 67.

I would expect setting the `step` argument to anything other than 0 would make that the exact amount the encoder will increment in.

**Comment by antonhornquist** [comment]
this issue is related to `Control` (which handles delta movements, they're too coarse right now - see #431) rather than `ControlSpec` (which just specifies the mapping of a control).

Apart from adding a way to make more fine grained deltas (#431) I agree we should consider stepping.

In the meantime I suggest to use `params:add_number()` which is designed to work with integers.

**Comment by tehn** [comment]
feel free to reopen if there is a more general issue that fine delta control doesn't provide (or the `number` param type)
