### ISSUE TITLE
midi/grid lib refinements

### ISSUE THREAD

**Issue by tehn** [monome/norns#534]
- [ ] remove "all"
- [ ] use "none" as default for vports
- [ ] automatically fill "none" ports with newly-plugged devices
- [ ] add `disconnect(x)` and `reconnect(x)` to script-side, where reconnect can redirect to another port number
- [ ] increase vports to 8 (?)

**Comment by simonvanderveldt** [comment]
Does this mean there will be no "all" functionality or will it be replaced, but now called "none" :?

**Comment by tehn** [comment]
"all" functionality is removed. if someone wants to send midi to all ports, they can iterate over the desired ports. if they want to receive from all ports, they can point multiple ports at the same event callback. i don't think "all" was ever a strong use-case, it was more a solution for having midi "just work" when plugged in. i believe this will now "just work" with auto-populating the vport list on connection.

"none" means nothing attached.

**Comment by TheTechnobear** [comment]
> i believe this will now "just work" with auto-populating the vport list on connection.

how will that work?
id assume each device will connect as a different midi virtual port... 
but if your script is going to do connect(1) then you'll just get the first device, which before you configure it will be random?

also perhaps a user has multiple controllers, and sometimes plugs in one of them, but other times wants to use another...  or perhaps they really don't mind which controller they use.

I will say I generally agree, once you have 'created your setup', its likely you'll want to use each controller for a particular 'role', but for more casual use - its a bit more difficult?!

**Comment by tehn** [comment]
auto-populate only happens on first-detection of a midi device. so a new build would start with everything set to "none" and the first detected midi device would go to slot 1. new devices would likewise populate to further ports. these ports can be assigned and moved around in SYSTEM > DEVICES

scripts can use a param to decide which vport they're using, thanks to the new inclusion of `reconnect`

so there are multiple levels of configuration, and i think everything you want to do will be both possible and easy.

**Comment by TheTechnobear** [comment]
cool, as you point out the most common case, is plugging in one controller when you first use norns and that'll work fine... also I think if a midi controller doesn't appear to work then users will natural go looking for a system setting to select it.

the only case I see slightly awkward still is the interchangeable controller scenario, which i'll try to illustrate.
say I have a keystep and a launchpad midi controller.... and I interchangeably use them, because sometimes I like the keystep, others the launchpad. … but I don't tend to use them together

let say first time we boot, we had keystep goes in slot 1.
next day, I choose to use the launchpad, but the config says keystep is in slot 1.
does this mean launchpad goes in slot 2...

(or does slot 1 always have the 'first midi controller' .. however that is defined!? )

If its in slot 2 that's a bit of a pain, since it means when you switch controllers, you have a choice
a) keep going to system->devices to move around
b) start editing scripts 

I think most daws have an 'all input source' for midi selectors, possibly for this reason..

anyway, im sure its fine for most users... not many are going to be moving around midi controllers that frequently :)

**Comment by tehn** [comment]
ah, i see your comment is deleted, but i take your point.

what i was suggesting (as darwin brought up) was to have the script define a parameter for which vport the script was using, which i believe solves your problem (yes, you do need to select the port in the param menu, not edit the script though). you can then even save psets that point at different ports if you wanted some sort of dynamic switching in runtime.
