### ISSUE TITLE
Menu gets stuck until Enc1 is turned in both directions

### ISSUE THREAD

**Issue by markwheeler** [monome/norns#775]
Frequently see this when returning to the menu from a script:
- Turn enc1 clockwise to move to the params page. The menu doesn't respond.
- Turning enc1 anti-clockwise, then clockwise again gets it moving correctly.

**Comment by tehn** [comment]
yikes. i'll check out the encoder sensitivity function. thanks for the heads up.

**Comment by markwheeler** [comment]
More detail for a sure repro:
- Go to a script's params menu.
- Now run a script from maiden on desktop.
- Short press KEY1 to return to the menu. You'll find yourself on the norns 'home' menu and unable to move to the right until you move to the left.

**Comment by okyeron** [comment]
FWIW - I see this same behavior as well on my Raspi setup. Must turn enc left and then back right to get params page.

**Comment by okyeron** [comment]
[menu.lua line 135](https://github.com/monome/norns/blob/67bbeba70e294bd5a966b8cf5b01dc60f93b0d08/lua/core/menu.lua#L135)
`local c = util.clamp(menu.panel+delta,1,4)` menu.panel is set to 4 because the prior screen was params. 

clicking enc 1 should reset this to menu.panel = 1?

or script load should reset menu.panel to 1?

If menu panel is 4 this will return 4

**Comment by tehn** [comment]
fixed. b6c4344..3e3b37d

script load auto-defaults EDIT screen to HOME now, and scrolling works as expected.
