### ISSUE TITLE
doc updates (general)

### ISSUE THREAD

**Issue by tehn** [monome/norns#862]
need to address common support issues. much of this information exists somewhere on the forum but is not centralized.

- [ ] AUDIO ERROR (ie, sc synth dupes)
- [ ] update failures (how to manually update)
- [ ] clean flash (with disk image link... etcher plus "manual" method)
- [ ] file management, library management, etc

main doc is here: https://github.com/monome/docs/blob/master/docs/norns/index.md

**Comment by okyeron** [comment]
Since I just had this happen (testing a new install), perhaps add this new error to the list

`error: SUPERCOLLIDER FAIL`

(which is probably network manager related in this case)

That aside - what's best here? Collect and post some forum links with fixes for these?

**Comment by tehn** [comment]
@okyeron i'd be very very interested to hear how you caused this error. the only reason it'll happen is when supercollider doesn't acknowledge loading, previously this was AUDIO ENGINE error. now we have DUPLICATE if this happens _and_ we scan the folder and find duplicates. generally i wouldn't expect to see SUPERCOLLIDER FAIL unless there's something really wrong with the setup

**Comment by okyeron** [comment]
Oh yeah - sorry... this is probably a way out edge case. My circumstances will probably never happen on Norns hardware.

I'm working on my RasPi install scripts, and in the process I start off using wpa_supplicant for wifi connection to get everything installed, then switch over to network manager once everything else is working properly.

This error happens before network manager is installed - i think because localhost is not configured properly yet and sc barfs or doesn't connect or something.

FWIW - I thought this was a new error in the update today and might need some documentation.

**Comment by tehn** [comment]
fixed, http://monome.org/docs/norns/help
