### ISSUE TITLE
built-in docs need regeneration

### ISSUE THREAD

**Issue by tehn** [monome/norns#935]
haven't been updated since april 😬

**Comment by pq** [comment]
oh boy.  it looks like there are a few stale spots and my change of output target needs some redirects (or re-thinking to work properly).

@tehn:  are you talking specifically about:

https://github.com/monome/norns/blob/gh-pages/index.html ?

(https://github.com/monome/norns/tree/master/doc should probably just go away altogether since we've moved over to gh-pages.)

**Comment by tehn** [comment]
ah, I meant the docs that live on the device via norns.local

I really think it's a matter of running ldoc and committing the changed files

**Comment by pq** [comment]
ok, got it!

**Comment by tehn** [comment]
@pq that said we should have some discussion about norns repo docs vs. monome docs and also preserving monome.org/norns as a product-detail page rather than API landing page
