### ISSUE TITLE
softcut API docs should be more descriptive

### ISSUE THREAD

**Issue by AndrewShike** [monome/norns#979]
I think a good chunk of these could use more detailed descriptions. I just wound up looking at source code to figure out what `voice_sync` did, which shouldn't be necessary. 

It's also confusing that the commands are using colon notation here, while the functions used do not.

(maybe this is already on a TODO list somewhere)

**Comment by catfact** [comment]
Not sure but I think the colon notation is applied automatically by luadoc when `@classmod` is used, or something

**Comment by catfact** [comment]
added a lot to the docstrings for this module. 

if there are specific confusions just lmk but i'll close this for now. 

ldoc output is kinda fugly but that's a different problem.

softcut also needs an actual manual, a very different problem (which is why i don't feel a need to go any more crazy on documenting the lua API - anything more thorough should live with the library)
